# Generated by Django 5.1.7 on 2025-05-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='after_pregnant',
            field=models.BooleanField(default=False),
        ),
    ]
