# Generated by Django 5.1.7 on 2025-05-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_after_pregnant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='week_of_pregnancy',
            field=models.IntegerField(default=0),
        ),
    ]
