# Generated by Django 5.1.7 on 2025-09-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_exercise_trimester_exercisevideo_exerciseset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='month_of_pregnancy',
        ),
    ]
