# Generated by Django 5.1.5 on 2025-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_month_of_pregnancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_pregnant',
            field=models.BooleanField(default=True),
        ),
    ]
