# Generated by Django 5.1.7 on 2025-10-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='single',
            field=models.BooleanField(default=False),
        ),
    ]
