# Generated by Django 5.1.7 on 2025-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_exerciseset_single'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisevideo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='set_counts',
            field=models.IntegerField(default=0),
        ),
    ]
