# Generated by Django 5.1.7 on 2025-10-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_exercisevideo_options_exerciseset_set_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='single',
        ),
        migrations.AddField(
            model_name='exercisevideo',
            name='single',
            field=models.BooleanField(default=False),
        ),
    ]
