# Generated by Django 5.1.7 on 2025-10-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_exerciseset_single_exercisevideo_single'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='set_counts',
        ),
    ]
