# Generated by Django 5.1.7 on 2025-12-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APKVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.IntegerField()),
                ('version_name', models.CharField(max_length=50)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('download_url', models.URLField()),
            ],
        ),
    ]
